spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@atlas.h5fd4y2.mongodb.net/?appName=Atlas
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  application:
    name: paymentservice
